name: Build e Deploy no GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  CLUSTER_NAME: cluster-kubernetes-padrao
  CLUSTER_REGION: us-central1
  DOCKER_IMAGE: aggosistemas/log-agent-backend

jobs:
  build-and-deploy:
    name: Build Docker e Deploy no GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker para Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

      - name: Configurar autenticação com GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar kubectl
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.CLUSTER_REGION }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Criar ou atualizar Secret GCP no cluster
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > ./gcp-sa-key.json
          kubectl delete secret gcp-secrets --ignore-not-found
          kubectl create secret generic gcp-secrets \
            --from-file=gcp-sa-key.json=./gcp-sa-key.json \
            --from-literal=GCP_PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"

      - name: Aplicar Deployment e Service
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
