apiVersion: v1
kind: Service
metadata:
  name: log-agent-backend-service
spec:
  type: LoadBalancer
  selector:
    app: log-agent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
